// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksI4ZUYENaJIfrju6gB6XOJv9f7tQcoY',
    appId: '1:354089240420:web:b1821d7fc1c5f339355c71',
    messagingSenderId: '354089240420',
    projectId: 'dynamic-link-app-df5f8',
    authDomain: 'dynamic-link-app-df5f8.firebaseapp.com',
    storageBucket: 'dynamic-link-app-df5f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPZloW9u_MnGrY16owYNJC1t5xq7v0_tw',
    appId: '1:354089240420:android:441ec14f834b9ced355c71',
    messagingSenderId: '354089240420',
    projectId: 'dynamic-link-app-df5f8',
    storageBucket: 'dynamic-link-app-df5f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4ofdG5PaIEdXv2P9iCsJyC4VLz1kHeQ',
    appId: '1:354089240420:ios:f0c123de20c6036a355c71',
    messagingSenderId: '354089240420',
    projectId: 'dynamic-link-app-df5f8',
    storageBucket: 'dynamic-link-app-df5f8.appspot.com',
    iosClientId: '354089240420-t3ujhihvjav632noae0a40ge4aiguc41.apps.googleusercontent.com',
    iosBundleId: 'com.example.dynamicLinkApp',
  );
}
